name: Maven Publish
on:
  release:
    types: [ prereleased, released ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7.0.0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Publish with Gradle to Repository
        env:
          REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: ./gradlew publish publishPlatformCompat
